import { Geist, Parkinsans, Delius } from 'next/font/google';
import './globals.css';
import { authOptions } from './api/auth/[...nextauth]/route';
import Providers from '../components/Providers';
import Navbar from '../components/Navbar';
import { getServerSession } from 'next-auth';

const parkinsans = Parkinsans({
  weight: ['400', '700'],
  subsets: ['latin'],
});

const delius = Delius({
  weight: ['400'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Quiz Pilot',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${parkinsans.className} antialiased bg-[#e8f0f8] dark:bg-[#131518] w-11/12 md:10/12 mx-auto max-w-7xl`}
      >
        <Providers session={session}>
          <Navbar />
          <main className="">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
