import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { authOptions } from './api/auth/[...nextauth]/route';
import Providers from '../components/Providers';
import Navbar from '../components/Navbar';
import { getServerSession } from 'next-auth';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Quiz Pilot',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
	const session = await getServerSession(authOptions);

	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<Providers session={session}>
					<Navbar />
					<main className=''>{children}</main>
				</Providers>
			</body>
		</html>
	);
}
