import { Geist, Parkinsans, Delius } from 'next/font/google';
import './globals.css';
import { authOptions } from './api/auth/[...nextauth]/route';
import Providers from '../components/Providers';
import Navbar from '../components/Navbar';
import { getServerSession } from 'next-auth';

const parkinsans = Parkinsans({
	weight: ['400', '700'],
	subsets: ['latin'],
});

const delius = Delius({
	weight: ['400'],
	subsets: ['latin'],
});

export const metadata = {
	title: 'Quiz Pilot',
	description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
	const session = await getServerSession(authOptions);

	return (
		<html lang='en' suppressHydrationWarning>
			{/* background color (light) ==>  #e8f0f8   bg-[#e8f0f8] */}
			{/* background color (dark) ==>  #131518   bg-[#131518] */}
			<body className={`${parkinsans.className} antialiased bg-background`}>
				<Providers session={session}>
					{/* <Navbar /> */}
					<main className='min-h-screen'>{children}</main>
				</Providers>
			</body>
		</html>
	);
}
